inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'junk/**/*'
    - 'lib/tasks/**/*'
    - 'spec/factories.rb'

Metrics/LineLength:
  # Change the default 80 chars limit value
  Max: 115
