# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48116e4da2b6a4925311133028db870263a44170c8c177ad82df17759f052047bd66e409792242dcb1ae182e05e2835c7444b06196403e41c6bd5cb65673617f
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_API_SECRET'] %>

test:
  secret_key_base: de8ff5ee939e73ca8c854c147358b66981b10ee5e63f314f52d4c42d0b2ed20d2d2faf8d4d3d3b510b21102308a4aa4926c88716d0f2656dec153775cfe6eaa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
